version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    # volumes:
      # - mysql-local:/var/lib/mysql
      # - type: bind
      #   source: ./initdb.d
      #   target: /docker-entrypoint-initdb.d
      # - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_ROOT_USER=$MYSQLDB_USER
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
# volumes:
#   mysql-local: